---
swagger: "2.0"
info:
  description: |
    Adherent api
  version: 1.0.8
  title: Adherent
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: adh6.minet.net
basePath: /api
tags:
- name: user
  description: Operations on users
- name: membership
  description: Manage membership records
- name: device
  description: Operations on devices
- name: room
  description: Operations on rooms
- name: switch
  description: Operations on switches
- name: port
  description: Operations on ports
schemes:
- https
paths:
  /user/:
    get:
      tags:
      - user
      summary: Filter users
      operationId: filterUser
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: Limit the number of users returned in the result. Default is 100
        required: false
        type: integer
        default: 100
      - name: offset
        in: query
        description: Skip the first n results
        required: false
        type: integer
        default: 0
      - name: terms
        in: query
        description: The generic search terms (will search in any field)
        required: false
        type: string
      - name: roomNumber
        in: query
        description: Filter by room number
        required: false
        type: integer
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
          headers:
            X-Total-Count:
              type: integer
              description: Total count of filtered entities
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.user
  /user/{username}:
    get:
      tags:
      - user
      summary: Retrieve an user
      operationId: getUser
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: The username of the user that needs to be fetched.
        required: true
        type: string
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/User'
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.user
    put:
      tags:
      - user
      summary: Update/create an user
      description: This can only be done by the logged in user.
      operationId: putUser
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: username of the user will be updated
        required: true
        type: string
      - in: body
        name: body
        description: New values of the user
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        201:
          description: Created
        204:
          description: Updated
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.user
    delete:
      tags:
      - user
      summary: Delete an user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: The username of the user that will be deleted
        required: true
        type: string
      responses:
        204:
          description: Deleted
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.user
  /user/{username}/password/:
    put:
      tags:
      - user
      summary: Update an user's password
      description: This can only be done by the logged in user.
      operationId: updatePassword
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: username of the user will be updated
        required: true
        type: string
      - in: body
        name: body
        description: New values of the user
        required: true
        schema:
          $ref: '#/definitions/password'
      responses:
        204:
          description: Modified
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.user
  /user/{username}/membership:
    post:
      tags:
      - membership
      summary: Add a membership record for an user
      operationId: addMembership
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: The username of the user
        required: true
        type: string
      - in: body
        name: body
        description: Membership record, if no start is specified, it will use the current date. Duration is expressed in days.
        required: true
        schema:
          $ref: '#/definitions/MembershipRecord'
      responses:
        200:
          description: Success
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.user
  /device/:
    get:
      tags:
      - device
      summary: Filter devices
      operationId: filterDevice
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: Limit the number of devices returned in the result. Default is 100
        required: false
        type: integer
        default: 100
      - name: offset
        in: query
        description: Skip the first n results
        required: false
        type: integer
        default: 0
      - name: username
        in: query
        description: Filter by owner's username
        required: false
        type: string
      - name: terms
        in: query
        description: Search terms
        required: false
        type: string
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
          headers:
            X-Total-Count:
              type: integer
              description: Total count of filtered entities
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.device
  /device/{macAddress}:
    get:
      tags:
      - device
      summary: Retrieve a device
      operationId: getDevice
      produces:
      - application/json
      parameters:
      - name: macAddress
        in: path
        description: The mac address of the device that will be fetched
        required: true
        type: string
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Device'
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.device
    put:
      tags:
      - device
      summary: Update/create a device
      operationId: putDevice
      produces:
      - application/json
      parameters:
      - name: macAddress
        in: path
        description: The mac address of the device that will be update
        required: true
        type: string
      - in: body
        name: body
        description: Device to update
        required: true
        schema:
          $ref: '#/definitions/Device'
      responses:
        201:
          description: Created
        204:
          description: Updated
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.device
    delete:
      tags:
      - device
      summary: Delete a device
      operationId: deleteDevice
      produces:
      - application/json
      parameters:
      - name: macAddress
        in: path
        description: The mac address of the device that will be deleted
        required: true
        type: string
      responses:
        204:
          description: Deleted
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.device
  /room/:
    get:
      tags:
      - room
      summary: Filter rooms
      operationId: filterRoom
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: Limit the number of rooms returned in the result. Default is 100
        required: false
        type: integer
        default: 100
      - name: offset
        in: query
        description: Skip the first n results
        required: false
        type: integer
        default: 0
      - name: terms
        in: query
        description: Search terms
        required: false
        type: string
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Room'
          headers:
            X-Total-Count:
              type: integer
              description: Total count of filtered entities
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.room
  /room/{roomNumber}:
    get:
      tags:
      - room
      summary: Retrieve a room
      operationId: getRoom
      produces:
      - application/json
      parameters:
      - name: roomNumber
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Room'
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.room
    put:
      tags:
      - room
      summary: Update/create a room
      operationId: putRoom
      produces:
      - application/json
      parameters:
      - name: roomNumber
        in: path
        required: true
        type: integer
      - in: body
        name: body
        description: Room to update
        required: true
        schema:
          $ref: '#/definitions/Room'
      responses:
        201:
          description: Created
        204:
          description: Updated
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.room
    delete:
      tags:
      - room
      summary: Delete a room
      operationId: deleteRoom
      produces:
      - application/json
      parameters:
      - name: roomNumber
        in: path
        required: true
        type: integer
      responses:
        204:
          description: Deleted
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.room
  /switch/:
    get:
      tags:
      - switch
      summary: Get all switches
      operationId: filterSwitch
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: Limit the number of switches returned in the result. Default is 100
        required: false
        type: integer
        default: 100
      - name: offset
        in: query
        description: Skip the first n results
        required: false
        type: integer
        default: 0
      - name: terms
        in: query
        description: Search terms
        required: false
        type: string
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Switch'
          headers:
            X-Total-Count:
              type: integer
              description: Total count of filtered entities
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.switch
    post:
      tags:
      - switch
      summary: Create a switch
      operationId: createSwitch
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Switch to create
        required: true
        schema:
          $ref: '#/definitions/Switch'
      responses:
        200:
          description: Created
          headers:
            Location:
              type: string
              description: URI to the newly created switch
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.switch
  /switch/{switchID}:
    get:
      tags:
      - switch
      summary: Retrieve a switch
      operationId: getSwitch
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Switch'
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.switch
    put:
      tags:
      - switch
      summary: Update a switch
      operationId: updateSwitch
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - in: body
        name: body
        description: Switch to update
        required: true
        schema:
          $ref: '#/definitions/Switch'
      responses:
        204:
          description: Updated
        400:
          description: Invalid input
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.switch
    delete:
      tags:
      - switch
      summary: Delete a switch
      operationId: deleteSwitch
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      responses:
        204:
          description: Deleted
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.switch
  /ports/:
    get:
      tags:
      - port
      summary: Filter ports
      operationId: filterPort
      produces:
      - application/json
      parameters:
      - name: limit
        in: query
        description: Limit the number of ports returned in the result. Default is 100
        required: false
        type: integer
        default: 100
      - name: offset
        in: query
        description: Skip the first n results
        required: false
        type: integer
        default: 0
      - name: switchID
        in: query
        description: Filter only ports that belongs to that switch
        required: false
        type: integer
      - name: roomNumber
        in: query
        description: Filter only ports that that room
        required: false
        type: integer
      - name: terms
        in: query
        description: Search terms
        required: false
        type: string
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Port'
          headers:
            X-Total-Count:
              type: integer
              description: Total count of filtered entities
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.port
  /switch/{switchID}/port/:
    post:
      tags:
      - port
      summary: Create a port
      operationId: createPort
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - in: body
        name: body
        description: Port to create
        required: true
        schema:
          $ref: '#/definitions/Port'
      responses:
        200:
          description: Created
          headers:
            Location:
              type: string
              description: URI to the newly created port
        400:
          description: Invalid input
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.port
  /switch/{switchID}/port/{portID}:
    get:
      tags:
      - port
      summary: Retrieve a port
      operationId: getPort
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - name: portID
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Port'
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.port
    put:
      tags:
      - port
      summary: Update a port
      operationId: updatePort
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - name: portID
        in: path
        required: true
        type: integer
      - in: body
        name: body
        description: Port to update
        required: true
        schema:
          $ref: '#/definitions/Port'
      responses:
        204:
          description: Updated
        400:
          description: Invalid input
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.port
    delete:
      tags:
      - port
      summary: Delete a port
      operationId: deletePort
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - name: portID
        in: path
        required: true
        type: integer
      responses:
        204:
          description: Deleted
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.port
  /switch/{switchID}/port/{portID}/state/:
    get:
      tags:
      - port
      summary: Retrieve the status of a port.
      operationId: getPortStatus
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - name: portID
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Success, false if it is shutdown, true otherwise
          schema:
            type: boolean
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.snmp_port
    put:
      tags:
      - port
      summary: Shutdown/enable a port
      operationId: setPortStatus
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - name: portID
        in: path
        required: true
        type: integer
      - in: body
        name: state
        description: True to open, False to shutdown
        required: true
        schema:
          type: boolean
      responses:
        204:
          description: Updated
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.snmp_port
  /switch/{switchID}/port/{portID}/vlan/:
    get:
      tags:
      - port
      summary: Retrieve the VLAN assigned to the port.
      operationId: getPortVlan
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - name: portID
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Success, returns 1 if the port has authentication on
          schema:
            type: integer
            example: 48
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.snmp_port
    put:
      tags:
      - port
      summary: Change the VLAN assigned a to port
      operationId: setPortVlan
      produces:
      - application/json
      parameters:
      - name: switchID
        in: path
        required: true
        type: integer
      - name: portID
        in: path
        required: true
        type: integer
      - in: body
        name: vlan
        description: VLAN to assign. Set it to 1 if you want to enable authentication on the port.
        required: true
        schema:
          type: integer
          example: "48"
      responses:
        204:
          description: Updated
        404:
          description: Not found
      security:
      - oauth2:
        - profile
      x-swagger-router-controller: adh.controller.snmp_port
securityDefinitions:
  oauth2:
    type: oauth2
    authorizationUrl: http://localhost:5000/oauth/authorize
    flow: implicit
    scopes:
      profile: access username & adh groups of user from LDAP
    x-tokenInfoFunc: adh.auth.token_info
definitions:
  User:
    type: object
    required:
    - email
    - firstName
    - lastName
    - username
    properties:
      email:
        type: string
        example: john.doe@gmail.com
      firstName:
        type: string
        example: John
      lastName:
        type: string
        example: Doe
      username:
        type: string
        example: doe_john
      departureDate:
        type: string
        format: date-time
      comment:
        type: string
      associationMode:
        type: string
        format: date-time
      roomNumber:
        type: integer
        format: int32
        example: 5012
    example:
      firstName: John
      lastName: Doe
      roomNumber: 5012
      comment: comment
      departureDate: 2000-01-23T04:56:07.000+00:00
      associationMode: 2000-01-23T04:56:07.000+00:00
      email: john.doe@gmail.com
      username: doe_john
  Device:
    type: object
    required:
    - connectionType
    - mac
    properties:
      mac:
        type: string
        example: 01:23:45:67:89:AB
      ipAddress:
        type: string
        example: 127.0.0.1
      ipv6Address:
        type: string
      connectionType:
        type: string
        enum:
        - wired
        - wireless
      username:
        type: string
        example: doe_john
    example:
      ipv6Address: ipv6Address
      ipAddress: 127.0.0.1
      connectionType: wired
      mac: 01:23:45:67:89:AB
      username: doe_john
  Room:
    type: object
    required:
    - roomNumber
    properties:
      description:
        type: string
        example: Chambre 5110
      roomNumber:
        type: integer
        example: 5110
      phone:
        type: integer
        example: 6842
      vlan:
        type: integer
        example: 45
    example:
      roomNumber: 5110
      vlan: 45
      phone: 6842
      description: Chambre 5110
  Port:
    type: object
    required:
    - portNumber
    properties:
      id:
        type: integer
        example: 1
      portNumber:
        type: string
        example: 1/0/4
      roomNumber:
        type: integer
        example: 5110
      switchID:
        type: integer
        example: 6
    example:
      roomNumber: 5110
      switchID: 6
      portNumber: 1/0/4
  Switch:
    type: object
    required:
    - community
    - ip
    properties:
      id:
        type: integer
        example: 1
      description:
        type: string
        example: Switch U5
      ip:
        type: string
        example: 192.168.102.211
      community:
        type: string
        format: password
        example: ghWgpQvHRkrYuqpMLWYkstS3
    example:
      ip: 192.168.102.211
      description: Switch U5
      community: ghWgpQvHRkrYuqpMLWYkstS3
  MembershipRecord:
    type: object
    required:
    - duration
    properties:
      start:
        type: string
        format: date-time
      duration:
        type: integer
        example: 365
        description: Duration in days
    example:
      duration: 365
      start: 2000-01-23T04:56:07.000+00:00
  password:
    type: object
    required:
    - password
    properties:
      password:
        type: string
        example: '&<Hs8XK/H+dT{7d7:=bxN~9;EqhwtW-;'
externalDocs:
  description: Find out more about MiNET
  url: http://minet.net
